version: '3.3'
networks:
  nginx-network:
    external: true
services:
  nginx-web:
    container_name: nginx
    image: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    networks:
      - nginx-network
